// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestwindSystem.Entities;

public partial class Shipper
{
    [Key]
    public int ShipperID { get; set; }

    [Required(ErrorMessage = "Company name is required.")]
    [StringLength(40, MinimumLength = 3)]
    public string CompanyName { get; set; }

    [Phone(ErrorMessage = "Invalid phone number.")]
    [StringLength(24)]
    public string Phone { get; set; }

    [InverseProperty("ShipViaNavigation")]
    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}